### ISSUE TITLE
[Issue] Bug with Northern Compass and Crossbowverhaul

### ISSUE THREAD

**Issue by MrHazMat** [DerToaster98/Crossbowverhaul#2]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [X] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
When charging the normal crossbow, there is no pulling string animation. The netherite crossbow and bezoar crossbow are not affected.

**To Reproduce**
1. Install Northern Compass and Crossbowverhaul
2. Get a normal crossbow
3. Charge the crossbow

**Screenshots**
![2022-02-14_10 27 19](https://user-images.githubusercontent.com/87276147/153789843-984a24d0-fc63-4b25-8d93-adc6730a0031.png)
![2022-02-14_10 27 33](https://user-images.githubusercontent.com/87276147/153789877-b67d99a9-1d53-4012-b767-b8da93be1e8b.png)

**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul: 1.2.4
Forge: 39.0.75
Minecraft: 1.18.1
Other mods (necessary to reproduce the bug): Northern Compass-1.0.8

**Comment by DerToaster98** [comment]
Can't really do something here, idk why it does not work, it works fine without Northern Compass.
Northern Compass probably changes something in the crossbow or the item predicates, so please report it to them

**Comment by MrHazMat** [comment]
I've reported it to them and the dev has released a fix for this

**Comment by DerToaster98** [comment]
Thanks!
