### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by OxiiGiin1** [DerToaster98/Crossbowverhaul#4]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x ] With a large modpack
   - [ ] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x ] Multiplayer
 - [x ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [x ] The game crashes because of this bug
 
**Describe the bug**

**To Reproduce**
1. Go to ...
2. Use item ...
3. Place block ...
4. ...

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul: 1.0.2
Forge: 36.2.33
Minecraft: 1.16.5

**Log File**
https://pastebin.com/q9rLw20M

**Comment by DerToaster98** [comment]
1.16.5 is no longer supported, thanks for the report though
