### ISSUE TITLE
Crash on "CrossbowAttackMob"

### ISSUE THREAD

**Issue by Fishbelt** [DerToaster98/Crossbowverhaul#5]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
  - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
Currently i think it's due to a village near the spawn chunks allways keeping the villagers and guards loaded 

**To Reproduce**
Can't replicate, happens aparently random

**Screenshots**
N/A
 
**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul: -1.18.1-1.2.4-universal
Forge: net.minecraftforge: 39.1.0
Minecraft: 1.18.1

Other mods (necessary to reproduce the bug): 
The crash reports mentions:
Guardvillagers
Apotheosis
supplementaries
structure gel

**Log File**
https://gist.github.com/Fishbelt/188d39b87f0ceacd3e511c58578eb160

**Comment by DerToaster98** [comment]
Please try if the issue still persists with the newest version of the mod (1.3.1), i don't support old versions, sorry.

**Comment by DerToaster98** [comment]
I think i know what might cause the issue though and it is fixed in development.

However, it is unlikely that i'll patch the bug on versions other than 1.18.2. I suggest you to wait until the patch it out and to then update the mod.

**Comment by DerToaster98** [comment]
To be clear: This won't be patched cause i no longer support 1.18.0 and 1.18.1, the only supported 1.18 version is 1.18.2 and the bug is patched there
