### ISSUE TITLE
All bolts do the same damage

### ISSUE THREAD

**Issue by DrPingas8** [DerToaster98/Crossbowverhaul#6]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [X] With a large modpack
   - [ ] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
All bolts do the same amounts of damage 

**To Reproduce**
1. Use Crossbow with different bolts

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul: 1.4.0
Forge: 40.1.19
Minecraft: 1.18.2
Other mods (necessary to reproduce the bug): 

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by DerToaster98** [comment]
And with what did you test if the damage actually is the same?

**Comment by DrPingas8** [comment]
I have tested it with many different health displays and without other mods

**Comment by DerToaster98** [comment]
hm, will look at it then. Just as a note. The "damage" of the bolts is not the actual damage it will do, it acts more like the base damage of it.

**Comment by DerToaster98** [comment]
Will be patched in the next update
