### ISSUE TITLE
Picking up a shot projectile only gives you a Iron Bolt

### ISSUE THREAD

**Issue by DaLumma** [DerToaster98/Crossbowverhaul#7]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [x] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
When shooting any bolt that is not the explosive bolt the projectile that is stuck in the ground only gives you the iron bolt item and not the exact bolt you shot.

**To Reproduce**
1. Shoot any bolt
2. Pick up the projectile
3. notice you have got a Iron bolt instead of the one you shot

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul: 1.4.0
Forge: 40.1.19
Minecraft: 1.18.2
Other mods (necessary to reproduce the bug):

**Log File**
https://gist.github.com/DaLumma/42e5f210c81581fdeb03af02f1e8a8ff

**Comment by DerToaster98** [comment]
Will be patched in the next update
