### ISSUE TITLE
Incompatibility with "Flintlock to Wheellock"

### ISSUE THREAD

**Issue by laptoppunk** [DerToaster98/Crossbowverhaul#8]
**General Information**
 - I play...
   - [X] With a large modpack
   - [ ] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [X] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [X] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
This version appears to make changes to the crossbow view model, which makes that resourcepack not work. The new flintlock models and variants load, but it breaks the animations

**To Reproduce**
1. Install a fresh 1.16.5 forge instance
2. Download and install Crossbowverhaul + dependencies 
2.5. Download and install https://www.planetminecraft.com/texture-pack/flintlock-to-wheellock/, place at top of resource load order
3. Make a new world, acquire a crossbow (now flintlock) 
4. Observe reload animation

**Screenshots**
https://streamable.com/3shd2f
 
**Versions**
Crossbowverhaul: MC1.16.5-1.0.3
Forge: 36.2.39
Minecraft: 1.16.5
Other mods (necessary to reproduce the bug): N/A

**Log File**
N/A

**Comment by laptoppunk** [comment]
Without Crossbowverual and dependencies, this is what it looks like https://streamable.com/2ryr3g

**Comment by DerToaster98** [comment]
Looks like the mod resources override the resourcepack.

Did you try changing the load order of the resourcepack so that it loads after mod resources?

Can't change the model files in the mod cause that would break the mod's visuals

**Comment by laptoppunk** [comment]
>Did you try changing the load order of the resourcepack so that it loads after mod resources

The resourcepack is placed above mod resources in the load order

**Comment by DerToaster98** [comment]
ye, you mentioned that, but did you try changing the order? I don't really remember if up or down has priority

**Comment by DerToaster98** [comment]
Will take a look in a few days when i'm home

**Comment by laptoppunk** [comment]
> ye, you mentioned that, but did you try changing the order? I don't really remember if up or down has priority

Up has priority. I can try swapping but I doubt it will help

**Comment by DerToaster98** [comment]
Checked today with the latest version of the resourcepack and it works just fine. It was a problem of the resourcepack.

**Comment by DerToaster98** [comment]
If it still doesn't work it most likely is a mod conflict. Then remove the mods one by one to find out which mod creates the conflict, if you found that, please create a new issue on the respective issue trackers of each conflicting mod

**Comment by laptoppunk** [comment]
https://github.com/LukeGrahamLandry/BetterCombat/issues/12

**Comment by laptoppunk** [comment]
https://github.com/AlexModGuy/Rats/issues/778

**Comment by laptoppunk** [comment]
https://www.curseforge.com/minecraft/mc-mods/spartan-shields/issues/79
