### ISSUE TITLE
Game fails to load after adding Crossbowverhall

### ISSUE THREAD

**Issue by TheRPGElite** [DerToaster98/Crossbowverhaul#9]
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [x ] With a large modpack
   - [ ] Only with Crossbowverhaul and it's dependencies
 - The issue occurs in...
   - [x ] Singleplayer
   - [ ] Multiplayer
 - [x ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x ] I reproduced the bug without any other mod's except forge, crossbowverhaul and it's dependencies
 - [x ] The game crashes because of this bug
 
**Describe the bug**
I have this and Forge version 47.1.0 installed.  The game fails to load after pressing PLAY on the Minecraft Launcher screen.  I have updated Forge to version 47.1.33 and this still occurs.  It fails to load giving me "Exit Code 1" as the only other info I can get.  

I noticed that along when I downloaded your mod, it also downloaded "MixinBootstap".  I disabled only this unknown mod and then yours loads fine.  The file for this is listed below.

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Crossbowverhaul:MC 1.20.1-1.7.1
Forge:47.1.00   AND   47.1.33
Minecraft:1.20.1
(  _MixinBootstrap-1.1.0.jar  ) this came with your mods download

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

**Comment by DerToaster98** [comment]
remove mixin bootstrap and provide a crash report next time please

**Comment by DerToaster98** [comment]
also you probably used some auto-mod-installing launcher didn't you?

Cause if yes then that launcher doesn't properly retrieve the dependencies for a mod. This mod (crossbowverhaul) depends on MixinBootstrap on 1.16. Since 1.18 it no longer depends on that and the curseforge releases are marked respectively.

**Comment by TheRPGElite** [comment]
No crash report generated as the game didn't even get to the loading screen, or I would have provided one.  Not my first ride at the rodeo.

    On Wednesday, July 19, 2023 at 03:03:04 AM CDT, DerToaster98 ***@***.***> wrote:  
 
 


remove mixin bootstrap and provide a crash report next time please

**Comment by TheRPGElite** [comment]
Also, I only install manually with the downloads from Curseforge.  Besides your note about needing the Mixinbootstrap for older versions (which I am not using), nothing indicates that it would ALSO download from the site.  

    On Thursday, July 20, 2023 at 01:32:29 AM CDT, Kingbls ***@***.***> wrote:  
 
  No crash report generated as the game didn't even get to the loading screen, or I would have provided one.  Not my first ride at the rodeo.

    On Wednesday, July 19, 2023 at 03:03:04 AM CDT, DerToaster98 ***@***.***> wrote:  
 
 


remove mixin bootstrap and provide a crash report next time please

**Comment by DerToaster98** [comment]
Weird, never had the issue where it would also download a dependency when downloading manually.

Again: IT IS NOT SUPPOSED to also download mixinbootstrap

**Comment by DerToaster98** [comment]
Just tested: when downloading normally from curseforge (version 1.7.1 for 1.20.1) it just downloads the main mod jar, so this is not an actual issue with curseforge or my mod. Issue locked.
